const frogFacts = [
"Isn't that amazing? Frogs have teeth on their upper jaws.",
"Ribbit-worthy! Frogs have teeth on their upper jaws.",
"Seriously cool. Some frogs care for their young.",
"Wow, right? Frogs existed before the dinosaurs.",
"Did you know? Some frogs can glide between trees.",
"Did you know? Tree frogs have specialized toe pads.",
"Seriously cool. Frogs can jump over 20 times their length.",
"Nature is wild. Frogs can jump over 20 times their length.",
"Seriously cool. Frogs have teeth on their upper jaws.",
"Nature is wild. The poison dart frog is extremely toxic.",
"Incredible stuff. Glass frogs have transparent skin.",
"Bet you didn’t know! Some frogs can freeze and survive.",
"Nature is wild. Frogs have teeth on their upper jaws.",
"Wow, right? Frogs eat insects with sticky tongues.",
"Ribbit-worthy! Glass frogs have transparent skin.",
"Nature is wild. Some frogs can glide between trees.",
"A true frog fact. Tree frogs have specialized toe pads.",
"A true frog fact. Frogs existed before the dinosaurs.",
"Frog life is fascinating. Frogs can breathe through their skin.",
"Wow, right? Some frogs care for their young.",
"Bet you didn’t know! The wood frog can survive freezing.",
"A true frog fact. Frogs don't drink water—they absorb it.",
"Wow, right? Frogs can jump over 20 times their length.",
"Wow, right? Glass frogs have transparent skin.",
"A true frog fact. Frogs can breathe through their skin.",
"Seriously cool. Frogs use their eyes to help swallow.",
"Ribbit-worthy! Frogs existed before the dinosaurs.",
"Isn't that amazing? There are over 6,000 frog species.",
"Incredible stuff. Tree frogs have specialized toe pads.",
"Incredible stuff. Frogs don't drink water—they absorb it.",
"Nature is wild. Frogs shed their skin and eat it.",
"Incredible stuff. Frogs shed their skin and eat it.",
"Did you know? Some frogs care for their young.",
"Bet you didn’t know! Frogs eat insects with sticky tongues.",
"Did you know? Frogs don't drink water—they absorb it.",
"Isn't that amazing? Frogs can jump over 20 times their length.",
"Incredible stuff. Frogs use their eyes to help swallow.",
"Bet you didn’t know! Frogs shed their skin and eat it.",
"Incredible stuff. Frogs can jump over 20 times their length.",
"Ribbit-worthy! Some frogs can glide between trees.",
"Isn't that amazing? Glass frogs have transparent skin.",
"Bet you didn’t know! Frogs use their eyes to help swallow.",
"A true frog fact. Frogs are important for the ecosystem.",
"Incredible stuff. Frogs eat insects with sticky tongues.",
"Incredible stuff. Frogs can breathe through their skin.",
"Incredible stuff. Frogs have teeth on their upper jaws.",
"Ribbit-worthy! Frogs can jump over 20 times their length.",
"A true frog fact. Some frogs glow under UV light.",
"Bet you didn’t know! The poison dart frog is extremely toxic.",
"Bet you didn’t know! Tree frogs have specialized toe pads.",
"Seriously cool. Some frogs glow under UV light.",
"A true frog fact. Glass frogs have transparent skin.",
"Bet you didn’t know! Frogs existed before the dinosaurs.",
"Did you know? Some frogs glow under UV light.",
"Wow, right? The poison dart frog is extremely toxic.",
"Incredible stuff. The poison dart frog is extremely toxic.",
"Bet you didn’t know! Glass frogs have transparent skin.",
"Ribbit-worthy! Frogs use their eyes to help swallow.",
"Seriously cool. The Goliath frog is the largest in the world.",
"Ribbit-worthy! Frogs don't drink water—they absorb it.",
"Isn't that amazing? Frogs shed their skin and eat it.",
"Seriously cool. Some frogs can glide between trees.",
"A true frog fact. Frogs use their eyes to help swallow.",
"Isn't that amazing? Some frogs care for their young.",
"Nature is wild. Some frogs glow under UV light.",
"Ribbit-worthy! Some frogs can freeze and survive.",
"Frog life is fascinating. Frogs can jump over 20 times their length.",
"Did you know? Frogs can breathe through their skin.",
"Seriously cool. Frogs eat insects with sticky tongues.",
"Frog life is fascinating. Frogs shed their skin and eat it.",
"Wow, right? Frogs can breathe through their skin.",
"Did you know? Frogs eat insects with sticky tongues.",
"Wow, right? Some frogs can freeze and survive.",
"Incredible stuff. Frogs existed before the dinosaurs.",
"Ribbit-worthy! Frogs croak to attract mates.",
"Isn't that amazing? Some frogs glow under UV light.",
"Nature is wild. The wood frog can survive freezing.",
"A true frog fact. Frogs shed their skin and eat it.",
"A true frog fact. Frogs eat insects with sticky tongues.",
"Frog life is fascinating. Glass frogs have transparent skin.",
"A true frog fact. Some frogs can glide between trees.",
"Frog life is fascinating. Tree frogs have specialized toe pads.",
"Ribbit-worthy! Frogs shed their skin and eat it.",
"Frog life is fascinating. Some frogs glow under UV light.",
"Bet you didn’t know! There are over 6,000 frog species.",
"Frog life is fascinating. The wood frog can survive freezing.",
"Wow, right? Some frogs glow under UV light.",
"Wow, right? Frogs are important for the ecosystem.",
"Nature is wild. Frogs eat insects with sticky tongues.",
"Did you know? Frogs are important for the ecosystem.",
"Isn't that amazing? Some frogs can freeze and survive.",
"Isn't that amazing? Frogs croak to attract mates.",
"Incredible stuff. There are over 6,000 frog species.",
"Frog life is fascinating. Some frogs can freeze and survive.",
"Frog life is fascinating. Some frogs care for their young.",
"Incredible stuff. Some frogs care for their young.",
"Bet you didn’t know! The Goliath frog is the largest in the world.",
"Nature is wild. Frogs use their eyes to help swallow.",
"Bet you didn’t know! Frogs can jump over 20 times their length.",
"Did you know? Glass frogs have transparent skin.",
"Wow, right? Frogs croak to attract mates.",
"Ribbit-worthy! The wood frog can survive freezing.",
"Seriously cool. Frogs croak to attract mates.",
"A true frog fact. The Goliath frog is the largest in the world.",
"Incredible stuff. Frogs croak to attract mates.",
"Frog life is fascinating. Frogs eat insects with sticky tongues.",
"Wow, right? The Goliath frog is the largest in the world.",
"Bet you didn’t know! Some frogs care for their young.",
"Frog life is fascinating. Some frogs can glide between trees.",
"Ribbit-worthy! Frogs are important for the ecosystem.",
"Frog life is fascinating. The poison dart frog is extremely toxic.",
"Did you know? Frogs have teeth on their upper jaws.",
"Incredible stuff. Some frogs can freeze and survive.",
"Did you know? The Goliath frog is the largest in the world.",
"Ribbit-worthy! The poison dart frog is extremely toxic.",
"Seriously cool. Frogs existed before the dinosaurs.",
"Frog life is fascinating. There are over 6,000 frog species.",
"Nature is wild. Tree frogs have specialized toe pads.",
"Seriously cool. Some frogs can freeze and survive.",
"Isn't that amazing? Frogs eat insects with sticky tongues.",
"Incredible stuff. Frogs are important for the ecosystem.",
"A true frog fact. There are over 6,000 frog species.",
"Wow, right? Frogs shed their skin and eat it.",
"Frog life is fascinating. The Goliath frog is the largest in the world.",
"Did you know? Frogs use their eyes to help swallow.",
"Wow, right? Tree frogs have specialized toe pads.",
"Frog life is fascinating. Frogs existed before the dinosaurs.",
"Isn't that amazing? Frogs can breathe through their skin.",
"Did you know? The wood frog can survive freezing.",
"Isn't that amazing? Frogs don't drink water—they absorb it.",
"Ribbit-worthy! Tree frogs have specialized toe pads.",
"Seriously cool. There are over 6,000 frog species.",
"Did you know? Frogs can jump over 20 times their length.",
"Isn't that amazing? Some frogs can glide between trees.",
"Isn't that amazing? Tree frogs have specialized toe pads.",
"Seriously cool. The poison dart frog is extremely toxic.",
"Bet you didn’t know! Frogs croak to attract mates.",
"A true frog fact. Frogs can jump over 20 times their length.",
"Incredible stuff. Some frogs can glide between trees.",
"Isn't that amazing? The Goliath frog is the largest in the world.",
"Bet you didn’t know! Frogs can breathe through their skin.",
"A true frog fact. Some frogs care for their young.",
"Seriously cool. Tree frogs have specialized toe pads.",
"Nature is wild. There are over 6,000 frog species.",
"Ribbit-worthy! Frogs can breathe through their skin.",
"Did you know? Frogs croak to attract mates.",
"A true frog fact. Frogs croak to attract mates.",
"Bet you didn’t know! Some frogs can glide between trees.",
"Wow, right? Frogs use their eyes to help swallow.",
"Wow, right? Frogs don't drink water—they absorb it.",
"Nature is wild. Some frogs can freeze and survive.",
"Nature is wild. Some frogs care for their young.",
"Ribbit-worthy! There are over 6,000 frog species.",
"Seriously cool. The wood frog can survive freezing.",
"Ribbit-worthy! Some frogs glow under UV light.",
"Ribbit-worthy! Frogs eat insects with sticky tongues.",
"Did you know? There are over 6,000 frog species.",
"Incredible stuff. The Goliath frog is the largest in the world.",
"Wow, right? There are over 6,000 frog species.",
"Bet you didn’t know! Some frogs glow under UV light.",
"Did you know? Some frogs can freeze and survive.",
"Isn't that amazing? Frogs existed before the dinosaurs.",
"A true frog fact. The poison dart frog is extremely toxic.",
"Did you know? The poison dart frog is extremely toxic.",
"Seriously cool. Frogs shed their skin and eat it.",
"Isn't that amazing? Frogs are important for the ecosystem.",
"A true frog fact. Some frogs can freeze and survive.",
"Wow, right? Frogs have teeth on their upper jaws.",
"Seriously cool. Glass frogs have transparent skin.",
"Nature is wild. Frogs can breathe through their skin.",
"Nature is wild. Frogs existed before the dinosaurs.",
"Wow, right? The wood frog can survive freezing.",
"A true frog fact. The wood frog can survive freezing.",
"Seriously cool. Frogs are important for the ecosystem.",
"Frog life is fascinating. Frogs have teeth on their upper jaws.",
"Seriously cool. Frogs don't drink water—they absorb it.",
"Bet you didn’t know! Frogs have teeth on their upper jaws.",
"Incredible stuff. The wood frog can survive freezing.",
"Nature is wild. The Goliath frog is the largest in the world.",
"Isn't that amazing? The wood frog can survive freezing.",
"Bet you didn’t know! Frogs are important for the ecosystem.",
"Ribbit-worthy! The Goliath frog is the largest in the world.",
"Isn't that amazing? Frogs use their eyes to help swallow.",
"Nature is wild. Glass frogs have transparent skin.",
"Ribbit-worthy! Some frogs care for their young.",
"Frog life is fascinating. Frogs are important for the ecosystem.",
"Nature is wild. Frogs are important for the ecosystem.",
"Nature is wild. Frogs don't drink water—they absorb it.",
"Isn't that amazing? The poison dart frog is extremely toxic.",
"Seriously cool. Frogs can breathe through their skin.",
"Wow, right? Some frogs can glide between trees.",
"Did you know? Frogs existed before the dinosaurs.",
"Frog life is fascinating. Frogs use their eyes to help swallow.",
"Nature is wild. Frogs croak to attract mates.",
"Incredible stuff. Some frogs glow under UV light.",
"Frog life is fascinating. Frogs croak to attract mates.",
"Did you know? Frogs shed their skin and eat it.",
"Bet you didn’t know! Frogs don't drink water—they absorb it.",
"A true frog fact. Frogs have teeth on their upper jaws.",
"Frog life is fascinating. Frogs don't drink water—they absorb it."
];